<?php

declare(strict_types=1);

/**
 * DatabaseBackupService — pure-PHP database backup (no exec/mysqldump required).
 *
 * Generates SQL dump files by querying table metadata and data directly via PDO.
 * Designed for cPanel environments where exec() is disabled.
 */
class DatabaseBackupService
{
  private static string $backupDir = '';

  private static function getBackupDir(): string
  {
    if (self::$backupDir === '') {
      self::$backupDir = __DIR__ . '/../storage/backups';
      if (!is_dir(self::$backupDir)) {
        mkdir(self::$backupDir, 0755, true);
      }
    }
    return self::$backupDir;
  }

  /**
   * Create a full SQL backup of the database.
   *
   * @return array{success: bool, file?: string, size?: int, error?: string}
   */
  public static function createBackup(): array
  {
    $db = Database::getConnection();
    $dbName = $_ENV['DB_NAME'] ?? 'avr_homes';
    $timestamp = date('Y-m-d_H-i-s');
    $filename = "backup_{$dbName}_{$timestamp}.sql";
    $filePath = self::getBackupDir() . '/' . $filename;

    $handle = @fopen($filePath, 'w');
    if (!$handle) {
      return ['success' => false, 'error' => 'Could not create backup file'];
    }

    // Header
    fwrite($handle, "-- AVR Homes Database Backup\n");
    fwrite($handle, "-- Database: {$dbName}\n");
    fwrite($handle, "-- Date: " . date('Y-m-d H:i:s') . "\n");
    fwrite($handle, "-- Generated by: DatabaseBackupService\n\n");
    fwrite($handle, "SET FOREIGN_KEY_CHECKS = 0;\n\n");

    // Get all tables
    $tables = $db->query("SHOW TABLES")->fetchAll(PDO::FETCH_NUM);
    $tableNames = array_column($tables, 0);

    foreach ($tableNames as $table) {
      // Table structure
      $createTable = $db->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_NUM);
      fwrite($handle, "DROP TABLE IF EXISTS `{$table}`;\n");
      fwrite($handle, $createTable[1] . ";\n\n");

      // Table data
      $rows = $db->query("SELECT * FROM `{$table}`")->fetchAll(PDO::FETCH_NUM);
      if (empty($rows)) continue;

      // Get column count to build INSERT statements
      $colCount = count($rows[0]);
      $placeholders = '(' . implode(',', array_fill(0, $colCount, '?')) . ')';

      // Get column names
      $cols = $db->query("SHOW COLUMNS FROM `{$table}`")->fetchAll(PDO::FETCH_NUM);
      $colNames = array_column($cols, 0);
      $escapedCols = array_map(fn($c) => "`{$c}`", $colNames);

      // Batch inserts (50 rows per statement for efficiency)
      $batchSize = 50;
      for ($i = 0; $i < count($rows); $i += $batchSize) {
        $batch = array_slice($rows, $i, $batchSize);
        $values = [];
        foreach ($batch as $row) {
          $values[] = $placeholders;
        }
        $sql = "INSERT INTO `{$table}` (" . implode(', ', $escapedCols) . ") VALUES\n";
        $sql .= implode(",\n", $values) . ";\n";
        fwrite($handle, $sql);
      }

      fwrite($handle, "\n");
    }

    fwrite($handle, "SET FOREIGN_KEY_CHECKS = 1;\n");
    fclose($handle);

    $size = filesize($filePath);

    // Keep only last 7 backups
    self::pruneOldBackups(7);

    return [
      'success' => true,
      'file'    => $filename,
      'size'    => $size,
    ];
  }

  /**
   * List available backups sorted newest-first.
   *
   * @return array<array{name: string, size: int, created: string}>
   */
  public static function listBackups(): array
  {
    $dir = self::getBackupDir();
    $files = glob($dir . '/backup_*.sql');
    if (!$files) return [];

    usort($files, fn($a, $b) => filemtime($b) - filemtime($a));

    return array_map(fn($f) => [
      'name'    => basename($f),
      'size'    => filesize($f),
      'created' => date('Y-m-d H:i:s', filemtime($f)),
    ], array_slice($files, 0, 20));
  }

  /**
   * Get the absolute path for a backup file.
   */
  public static function getBackupPath(string $filename): ?string
  {
    $path = self::getBackupDir() . '/' . basename($filename);
    return file_exists($path) ? $path : null;
  }

  /**
   * Delete old backups, keeping only the most recent $keep files.
   */
  private static function pruneOldBackups(int $keep): void
  {
    $dir = self::getBackupDir();
    $files = glob($dir . '/backup_*.sql');
    if (!$files || count($files) <= $keep) return;

    usort($files, fn($a, $b) => filemtime($b) - filemtime($a));

    $toDelete = array_slice($files, $keep);
    foreach ($toDelete as $f) {
      @unlink($f);
    }
  }
}
