/**
 * Database backup service for the Next.js server layer.
 *
 * Generates SQL dump files by querying table metadata and data directly,
 * mirroring the legacy PHP `DatabaseBackupService`.
 *
 * @module server/backup
 */

import { rawQuery } from "@/server/db";
import { mkdirSync, writeFileSync, readdirSync, unlinkSync, statSync, existsSync } from "node:fs";
import path from "node:path";

let backupDir = "";

function getBackupDir(): string {
  if (backupDir === "") {
    backupDir = path.join(process.cwd(), "backend", "storage", "backups");
    if (!existsSync(backupDir)) {
      mkdirSync(backupDir, { recursive: true });
    }
  }
  return backupDir;
}

function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  const str = String(value);
  return `'${str.replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
}

/**
 * Create a full SQL backup of the database.
 */
export async function createBackup(): Promise<{ success: boolean; file?: string; size?: number; error?: string }> {
  const dbName = process.env.DB_NAME ?? "avr_homes";
  const timestamp = new Date().toISOString().replace(/[:T]/g, "-").slice(0, 19);
  const filename = `backup_${dbName}_${timestamp}.sql`;
  const filePath = path.join(getBackupDir(), filename);

  const lines: string[] = [];
  lines.push("-- AVR Homes Database Backup");
  lines.push(`-- Database: ${dbName}`);
  lines.push("-- Date: " + new Date().toISOString().replace("T", " ").slice(0, 19));
  lines.push("-- Generated by: DatabaseBackupService");
  lines.push("");
  lines.push("SET FOREIGN_KEY_CHECKS = 0;");
  lines.push("");

  let tables: any[];
  try {
    tables = await rawQuery("SHOW TABLES");
  } catch (e: any) {
    return { success: false, error: "Could not list tables: " + (e?.message ?? "Unknown error") };
  }

  const tableNames = tables.map((t: any) => Object.values(t)[0]);

  for (const table of tableNames) {
    let createResult: any;
    try {
      createResult = await rawQuery(`SHOW CREATE TABLE \`${table}\``);
    } catch (e: any) {
      continue;
    }
    const createSql = Object.values(createResult[0] ?? {})[1] ?? "";
    lines.push(`DROP TABLE IF EXISTS \`${table}\`;`);
    lines.push(String(createSql) + ";");
    lines.push("");

    let rows: any[];
    try {
      rows = await rawQuery(`SELECT * FROM \`${table}\``);
    } catch (e: any) {
      continue;
    }
    if (!rows || rows.length === 0) continue;

    const colNames = Object.keys(rows[0]);
    const escapedCols = colNames.map((c) => `\`${c}\``);

    const batchSize = 50;
    for (let i = 0; i < rows.length; i += batchSize) {
      const batch = rows.slice(i, i + batchSize);
      const valueLines = batch.map((row) =>
        "(" + colNames.map((c) => sqlValue(row[c])).join(", ") + ")"
      );
      lines.push(
        `INSERT INTO \`${table}\` (${escapedCols.join(", ")}) VALUES\n` +
        valueLines.join(",\n") + ";"
      );
    }
    lines.push("");
  }

  lines.push("SET FOREIGN_KEY_CHECKS = 1;");
  lines.push("");

  writeFileSync(filePath, lines.join("\n"), "utf8");
  const size = statSync(filePath).size;

  pruneOldBackups(7);

  return { success: true, file: filename, size };
}

/**
 * List available backups sorted newest-first (max 20).
 */
export async function listBackups(): Promise<{ name: string; size: number; created: string }[]> {
  const dir = getBackupDir();
  if (!existsSync(dir)) return [];
  const files = readdirSync(dir).filter((f) => f.startsWith("backup_") && f.endsWith(".sql"));

  const backups = files.map((f) => {
    const st = statSync(path.join(dir, f));
    return {
      name: f,
      size: st.size,
      created: new Date(st.mtimeMs).toISOString().replace("T", " ").slice(0, 19),
    };
  });

  backups.sort((a, b) => b.created.localeCompare(a.created));
  return backups.slice(0, 20);
}

/**
 * Get the absolute path for a backup file, or null.
 */
export function getBackupPath(filename: string): string | null {
  const safe = path.basename(filename);
  const p = path.join(getBackupDir(), safe);
  return existsSync(p) ? p : null;
}

/**
 * Delete old backups, keeping only the most recent `keep`.
 */
function pruneOldBackups(keep: number): void {
  const dir = getBackupDir();
  if (!existsSync(dir)) return;
  const files = readdirSync(dir).filter((f) => f.startsWith("backup_") && f.endsWith(".sql"));
  if (files.length <= keep) return;

  const sorted = files
    .map((f) => ({ f, m: statSync(path.join(dir, f)).mtimeMs }))
    .sort((a, b) => b.m - a.m);

  for (const { f } of sorted.slice(keep)) {
    try {
      unlinkSync(path.join(dir, f));
    } catch (e: any) {
      // best-effort
    }
  }
}
