/**
 * Database connection pool for the Next.js server layer.
 *
 * Mirrors the legacy PDO connection from the PHP backend using `mysql2/promise`.
 * Exposes `query`, `fetchOne`, `fetchAll`, and transaction helpers that
 * mirror the PDO prepared-statement style used throughout the ported controllers.
 *
 * @module server/db
 */

import mysql, { type Pool } from "mysql2/promise";

let pool: Pool | null = null;

function getPool(): Pool {
  if (!pool) {
    pool = mysql.createPool({
      host: process.env.DB_HOST ?? "127.0.0.1",
      port: Number(process.env.DB_PORT ?? 3306),
      database: process.env.DB_NAME ?? "avr_homes",
      user: process.env.DB_USER ?? "root",
      password: process.env.DB_PASS ?? "",
      waitForConnections: true,
      connectionLimit: 10,
      charset: "utf8mb4",
      namedPlaceholders: false,
      decimalNumbers: true,
      dateStrings: true,
    });
  }
  return pool;
}

/** A single database connection (used for transactions). */
export type DbConnection = mysql.PoolConnection;

export interface QueryResult {
  insertId: number;
  affectedRows: number;
}

/**
 * Run a prepared-statement query with positional `?` placeholders.
 *
 * @param sql   SQL with `?` placeholders.
 * @param params Bound parameter values.
 * @returns The raw result (rows for SELECT, OkPacket for writes).
 */
export async function query(sql: string, params: unknown[] = []): Promise<any> {
  const [rows] = await getPool().execute(sql, params as any[]);
  return rows;
}

/**
 * Fetch a single row (or null) from a prepared query.
 */
export async function fetchOne(sql: string, params: unknown[] = []): Promise<any | null> {
  const [rows] = await getPool().execute(sql, params as any[]);
  return Array.isArray(rows) ? (rows[0] ?? null) : null;
}

/**
 * Fetch all rows from a prepared query.
 */
export async function fetchAll(sql: string, params: unknown[] = []): Promise<any[]> {
  const [rows] = await getPool().execute(sql, params as any[]);
  return Array.isArray(rows) ? rows : [];
}

/**
 * Run a raw (non-prepared) statement via the text protocol. Used for DDL,
 * `SHOW ...` introspection, and multi-statement migration files where the
 * prepared-statement path is unsupported. Returns rows for SELECT/SHOW, or
 * an OkPacket-style result for writes.
 */
export async function rawQuery(sql: string): Promise<any> {
  const [result] = await getPool().query(sql);
  return result;
}

/**
 * Execute a write statement and return the raw result (insertId, affectedRows).
 */
export async function execute(sql: string, params: unknown[] = []): Promise<QueryResult> {
  const [result] = await getPool().execute(sql, params as any[]);
  return result as unknown as QueryResult;
}

/**
 * Returns the last auto-increment ID generated by the given insert result.
 */
export function lastInsertId(result: QueryResult): number {
  return Number(result?.insertId ?? 0);
}

/**
 * Begin a transaction. Returns a pooled connection that callers must pass to
 * `txQuery` / `txExecute` and commit / rollback.
 */
export async function beginTransaction(): Promise<DbConnection> {
  const conn = await getPool().getConnection();
  await conn.beginTransaction();
  return conn;
}

/** Execute a query within the given transaction connection. */
export async function txQuery(conn: DbConnection, sql: string, params: unknown[] = []): Promise<any> {
  const [rows] = await conn.execute(sql, params as any[]);
  return rows;
}

/** Fetch a single row within a transaction. */
export async function txFetchOne(conn: DbConnection, sql: string, params: unknown[] = []): Promise<any | null> {
  const [rows] = await conn.execute(sql, params as any[]);
  return Array.isArray(rows) ? (rows[0] ?? null) : null;
}

/** Execute a write within a transaction connection. */
export async function txExecute(conn: DbConnection, sql: string, params: unknown[] = []): Promise<QueryResult> {
  const [result] = await conn.execute(sql, params as any[]);
  return result as unknown as QueryResult;
}

/** Commit an open transaction. */
export async function commit(conn: DbConnection): Promise<void> {
  await conn.commit();
  conn.release();
}

/** Roll back an open transaction. */
export async function rollback(conn: DbConnection): Promise<void> {
  await conn.rollback();
  conn.release();
}

/** Close the pool (used in tests / teardown). */
export async function closeDb(): Promise<void> {
  if (pool) {
    await pool.end();
    pool = null;
  }
}
