-- Migration 023: Pooled property investment (ajo/esusu group contribution scheme)
-- People pool money monthly or one-time toward a target property. Contributions are
-- tracked per account, held in the company account until the target is funded.
-- Late monthly payments incur a penalty after a grace period. 3 email reminders
-- are sent before each due date.
--
-- NOTE: No foreign keys (MyISAM compatibility on shared hosting).

-- The pooled purchase project
CREATE TABLE IF NOT EXISTS investment_pools (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NULL,
  image VARCHAR(500) NULL,
  target_property_id INT UNSIGNED NULL,
  target_amount DECIMAL(18,2) NOT NULL,
  current_raised DECIMAL(18,2) NOT NULL DEFAULT 0,
  member_count INT UNSIGNED NOT NULL DEFAULT 0,
  default_monthly DECIMAL(15,2) NULL,
  min_monthly DECIMAL(15,2) NULL,
  max_monthly DECIMAL(15,2) NULL,
  min_lump_sum DECIMAL(15,2) NULL,
  allow_monthly TINYINT(1) NOT NULL DEFAULT 1,
  allow_lump_sum TINYINT(1) NOT NULL DEFAULT 1,
  penalty_rate DECIMAL(5,2) NOT NULL DEFAULT 5.00 COMMENT 'Late payment penalty %',
  grace_days INT NOT NULL DEFAULT 7 COMMENT 'Days after due date before penalty applies',
  default_after_days INT NOT NULL DEFAULT 30 COMMENT 'Days after due date to mark member as defaulted',
  reminder_days_before VARCHAR(50) NOT NULL DEFAULT '7,3,1' COMMENT 'Days before due date to send reminders',
  start_date DATE NULL,
  end_date DATE NULL,
  status ENUM('draft','active','paused','funded','completed','closed') NOT NULL DEFAULT 'active',
  funded_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pool_status (status),
  INDEX idx_pool_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A user's participation in a pool (monthly and/or one-time plan)
CREATE TABLE IF NOT EXISTS pool_memberships (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pool_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  plan_type ENUM('monthly','lump_sum','both') NOT NULL DEFAULT 'monthly',
  monthly_amount DECIMAL(15,2) NULL,
  paystack_customer_code VARCHAR(100) NULL,
  paystack_plan_code VARCHAR(100) NULL,
  paystack_subscription_code VARCHAR(100) NULL,
  auto_debit TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('active','paused','defaulted','completed','withdrawn') NOT NULL DEFAULT 'active',
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_membership_pool (pool_id),
  INDEX idx_membership_user (user_id),
  INDEX idx_membership_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Monthly payment installments generated by the cron job
CREATE TABLE IF NOT EXISTS pool_schedules (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  membership_id INT UNSIGNED NOT NULL,
  pool_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  due_date DATE NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  penalty_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_due DECIMAL(15,2) NOT NULL,
  status ENUM('pending','paid','overdue','defaulted','skipped') NOT NULL DEFAULT 'pending',
  paid_at TIMESTAMP NULL,
  penalty_applied_at TIMESTAMP NULL,
  payment_ref VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_schedule_membership (membership_id),
  INDEX idx_schedule_pool (pool_id),
  INDEX idx_schedule_user (user_id),
  INDEX idx_schedule_due (due_date),
  INDEX idx_schedule_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Every payment received (monthly, lump sum, penalty) — the money trail
CREATE TABLE IF NOT EXISTS pool_contributions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pool_id INT UNSIGNED NOT NULL,
  membership_id INT UNSIGNED NULL,
  user_id INT UNSIGNED NOT NULL,
  schedule_id INT UNSIGNED NULL,
  amount DECIMAL(15,2) NOT NULL,
  penalty_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  type ENUM('monthly','lump_sum','penalty','refund') NOT NULL DEFAULT 'monthly',
  channel ENUM('auto_debit','manual','transfer') NOT NULL DEFAULT 'manual',
  payment_ref VARCHAR(100) NULL,
  status ENUM('pending','paid','failed') NOT NULL DEFAULT 'paid',
  paid_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_contrib_pool (pool_id),
  INDEX idx_contrib_membership (membership_id),
  INDEX idx_contrib_user (user_id),
  INDEX idx_contrib_schedule (schedule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Log of reminders, penalty, and payment notifications sent
CREATE TABLE IF NOT EXISTS pool_notifications (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pool_id INT UNSIGNED NOT NULL,
  membership_id INT UNSIGNED NULL,
  user_id INT UNSIGNED NOT NULL,
  schedule_id INT UNSIGNED NULL,
  type ENUM('reminder','overdue','penalty','welcome','payment','default','info') NOT NULL DEFAULT 'info',
  channel ENUM('email','whatsapp','sms','in_app') NOT NULL DEFAULT 'email',
  subject VARCHAR(255) NULL,
  body TEXT NULL,
  days_before INT NULL,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_notif_membership (membership_id),
  INDEX idx_notif_user (user_id),
  INDEX idx_notif_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
