/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortletRouteImport } from './routes/shortlet'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RentRouteImport } from './routes/rent'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as MarketInsightsRouteImport } from './routes/market-insights'
import { Route as MapRouteImport } from './routes/map'
import { Route as LandRouteImport } from './routes/land'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DiasporaRouteImport } from './routes/diaspora'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai-search'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as AgentRegisterRouteImport } from './routes/agent.register'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AgentDashboardVerificationRouteImport } from './routes/agent.dashboard.verification'
import { Route as AgentDashboardSubscriptionsRouteImport } from './routes/agent.dashboard.subscriptions'
import { Route as AgentDashboardReferralsRouteImport } from './routes/agent.dashboard.referrals'
import { Route as AgentDashboardProfileRouteImport } from './routes/agent.dashboard.profile'
import { Route as AgentDashboardListingsRouteImport } from './routes/agent.dashboard.listings'
import { Route as AgentDashboardLeadsRouteImport } from './routes/agent.dashboard.leads'
import { Route as AgentDashboardBlogRouteImport } from './routes/agent.dashboard.blog'
import { Route as AdminPropertiesCreateRouteImport } from './routes/admin.properties.create'
import { Route as AgentDashboardListingsCreateRouteImport } from './routes/agent.dashboard.listings.create'
import { Route as AgentDashboardListingsIdEditRouteImport } from './routes/agent.dashboard.listings.$id.edit'

const ShortletRoute = ShortletRouteImport.update({
  id: '/shortlet',
  path: '/shortlet',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketInsightsRoute = MarketInsightsRouteImport.update({
  id: '/market-insights',
  path: '/market-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DiasporaRoute = DiasporaRouteImport.update({
  id: '/diaspora',
  path: '/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai-search',
  path: '/api/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentRegisterRoute = AgentRegisterRouteImport.update({
  id: '/agent/register',
  path: '/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AgentDashboardVerificationRoute =
  AgentDashboardVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AgentDashboardRoute,
  } as any)
const AgentDashboardSubscriptionsRoute =
  AgentDashboardSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AgentDashboardRoute,
  } as any)
const AgentDashboardReferralsRoute = AgentDashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardProfileRoute = AgentDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardListingsRoute = AgentDashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardLeadsRoute = AgentDashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardBlogRoute = AgentDashboardBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AdminPropertiesCreateRoute = AdminPropertiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminPropertiesRoute,
} as any)
const AgentDashboardListingsCreateRoute =
  AgentDashboardListingsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AgentDashboardListingsRoute,
  } as any)
const AgentDashboardListingsIdEditRoute =
  AgentDashboardListingsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AgentDashboardListingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/insights': typeof InsightsRoute
  '/land': typeof LandRoute
  '/map': typeof MapRoute
  '/market-insights': typeof MarketInsightsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/rent': typeof RentRoute
  '/saved': typeof SavedRoute
  '/shortlet': typeof ShortletRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/agent/dashboard': typeof AgentDashboardRouteWithChildren
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/ai-search': typeof ApiAiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/properties/create': typeof AdminPropertiesCreateRoute
  '/agent/dashboard/blog': typeof AgentDashboardBlogRoute
  '/agent/dashboard/leads': typeof AgentDashboardLeadsRoute
  '/agent/dashboard/listings': typeof AgentDashboardListingsRouteWithChildren
  '/agent/dashboard/profile': typeof AgentDashboardProfileRoute
  '/agent/dashboard/referrals': typeof AgentDashboardReferralsRoute
  '/agent/dashboard/subscriptions': typeof AgentDashboardSubscriptionsRoute
  '/agent/dashboard/verification': typeof AgentDashboardVerificationRoute
  '/agent/dashboard/listings/create': typeof AgentDashboardListingsCreateRoute
  '/agent/dashboard/listings/$id/edit': typeof AgentDashboardListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/insights': typeof InsightsRoute
  '/land': typeof LandRoute
  '/map': typeof MapRoute
  '/market-insights': typeof MarketInsightsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/rent': typeof RentRoute
  '/saved': typeof SavedRoute
  '/shortlet': typeof ShortletRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/agent/dashboard': typeof AgentDashboardRouteWithChildren
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/ai-search': typeof ApiAiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/properties/create': typeof AdminPropertiesCreateRoute
  '/agent/dashboard/blog': typeof AgentDashboardBlogRoute
  '/agent/dashboard/leads': typeof AgentDashboardLeadsRoute
  '/agent/dashboard/listings': typeof AgentDashboardListingsRouteWithChildren
  '/agent/dashboard/profile': typeof AgentDashboardProfileRoute
  '/agent/dashboard/referrals': typeof AgentDashboardReferralsRoute
  '/agent/dashboard/subscriptions': typeof AgentDashboardSubscriptionsRoute
  '/agent/dashboard/verification': typeof AgentDashboardVerificationRoute
  '/agent/dashboard/listings/create': typeof AgentDashboardListingsCreateRoute
  '/agent/dashboard/listings/$id/edit': typeof AgentDashboardListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/insights': typeof InsightsRoute
  '/land': typeof LandRoute
  '/map': typeof MapRoute
  '/market-insights': typeof MarketInsightsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/rent': typeof RentRoute
  '/saved': typeof SavedRoute
  '/shortlet': typeof ShortletRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/agent/dashboard': typeof AgentDashboardRouteWithChildren
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/ai-search': typeof ApiAiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/properties/create': typeof AdminPropertiesCreateRoute
  '/agent/dashboard/blog': typeof AgentDashboardBlogRoute
  '/agent/dashboard/leads': typeof AgentDashboardLeadsRoute
  '/agent/dashboard/listings': typeof AgentDashboardListingsRouteWithChildren
  '/agent/dashboard/profile': typeof AgentDashboardProfileRoute
  '/agent/dashboard/referrals': typeof AgentDashboardReferralsRoute
  '/agent/dashboard/subscriptions': typeof AgentDashboardSubscriptionsRoute
  '/agent/dashboard/verification': typeof AgentDashboardVerificationRoute
  '/agent/dashboard/listings/create': typeof AgentDashboardListingsCreateRoute
  '/agent/dashboard/listings/$id/edit': typeof AgentDashboardListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/buy'
    | '/contact'
    | '/diaspora'
    | '/insights'
    | '/land'
    | '/map'
    | '/market-insights'
    | '/properties'
    | '/rent'
    | '/saved'
    | '/shortlet'
    | '/admin/activity'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/agent/dashboard'
    | '/agent/login'
    | '/agent/register'
    | '/agents/$slug'
    | '/api/ai-search'
    | '/blog/$slug'
    | '/properties/$id'
    | '/admin/properties/create'
    | '/agent/dashboard/blog'
    | '/agent/dashboard/leads'
    | '/agent/dashboard/listings'
    | '/agent/dashboard/profile'
    | '/agent/dashboard/referrals'
    | '/agent/dashboard/subscriptions'
    | '/agent/dashboard/verification'
    | '/agent/dashboard/listings/create'
    | '/agent/dashboard/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/buy'
    | '/contact'
    | '/diaspora'
    | '/insights'
    | '/land'
    | '/map'
    | '/market-insights'
    | '/properties'
    | '/rent'
    | '/saved'
    | '/shortlet'
    | '/admin/activity'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/agent/dashboard'
    | '/agent/login'
    | '/agent/register'
    | '/agents/$slug'
    | '/api/ai-search'
    | '/blog/$slug'
    | '/properties/$id'
    | '/admin/properties/create'
    | '/agent/dashboard/blog'
    | '/agent/dashboard/leads'
    | '/agent/dashboard/listings'
    | '/agent/dashboard/profile'
    | '/agent/dashboard/referrals'
    | '/agent/dashboard/subscriptions'
    | '/agent/dashboard/verification'
    | '/agent/dashboard/listings/create'
    | '/agent/dashboard/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/buy'
    | '/contact'
    | '/diaspora'
    | '/insights'
    | '/land'
    | '/map'
    | '/market-insights'
    | '/properties'
    | '/rent'
    | '/saved'
    | '/shortlet'
    | '/admin/activity'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/agent/dashboard'
    | '/agent/login'
    | '/agent/register'
    | '/agents/$slug'
    | '/api/ai-search'
    | '/blog/$slug'
    | '/properties/$id'
    | '/admin/properties/create'
    | '/agent/dashboard/blog'
    | '/agent/dashboard/leads'
    | '/agent/dashboard/listings'
    | '/agent/dashboard/profile'
    | '/agent/dashboard/referrals'
    | '/agent/dashboard/subscriptions'
    | '/agent/dashboard/verification'
    | '/agent/dashboard/listings/create'
    | '/agent/dashboard/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  DiasporaRoute: typeof DiasporaRoute
  InsightsRoute: typeof InsightsRoute
  LandRoute: typeof LandRoute
  MapRoute: typeof MapRoute
  MarketInsightsRoute: typeof MarketInsightsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RentRoute: typeof RentRoute
  SavedRoute: typeof SavedRoute
  ShortletRoute: typeof ShortletRoute
  AgentDashboardRoute: typeof AgentDashboardRouteWithChildren
  AgentLoginRoute: typeof AgentLoginRoute
  AgentRegisterRoute: typeof AgentRegisterRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortlet': {
      id: '/shortlet'
      path: '/shortlet'
      fullPath: '/shortlet'
      preLoaderRoute: typeof ShortletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-insights': {
      id: '/market-insights'
      path: '/market-insights'
      fullPath: '/market-insights'
      preLoaderRoute: typeof MarketInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaspora': {
      id: '/diaspora'
      path: '/diaspora'
      fullPath: '/diaspora'
      preLoaderRoute: typeof DiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/ai-search': {
      id: '/api/ai-search'
      path: '/api/ai-search'
      fullPath: '/api/ai-search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agent/register': {
      id: '/agent/register'
      path: '/agent/register'
      fullPath: '/agent/register'
      preLoaderRoute: typeof AgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/dashboard/verification': {
      id: '/agent/dashboard/verification'
      path: '/verification'
      fullPath: '/agent/dashboard/verification'
      preLoaderRoute: typeof AgentDashboardVerificationRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/subscriptions': {
      id: '/agent/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/agent/dashboard/subscriptions'
      preLoaderRoute: typeof AgentDashboardSubscriptionsRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/referrals': {
      id: '/agent/dashboard/referrals'
      path: '/referrals'
      fullPath: '/agent/dashboard/referrals'
      preLoaderRoute: typeof AgentDashboardReferralsRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/profile': {
      id: '/agent/dashboard/profile'
      path: '/profile'
      fullPath: '/agent/dashboard/profile'
      preLoaderRoute: typeof AgentDashboardProfileRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/listings': {
      id: '/agent/dashboard/listings'
      path: '/listings'
      fullPath: '/agent/dashboard/listings'
      preLoaderRoute: typeof AgentDashboardListingsRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/leads': {
      id: '/agent/dashboard/leads'
      path: '/leads'
      fullPath: '/agent/dashboard/leads'
      preLoaderRoute: typeof AgentDashboardLeadsRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/blog': {
      id: '/agent/dashboard/blog'
      path: '/blog'
      fullPath: '/agent/dashboard/blog'
      preLoaderRoute: typeof AgentDashboardBlogRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/admin/properties/create': {
      id: '/admin/properties/create'
      path: '/create'
      fullPath: '/admin/properties/create'
      preLoaderRoute: typeof AdminPropertiesCreateRouteImport
      parentRoute: typeof AdminPropertiesRoute
    }
    '/agent/dashboard/listings/create': {
      id: '/agent/dashboard/listings/create'
      path: '/create'
      fullPath: '/agent/dashboard/listings/create'
      preLoaderRoute: typeof AgentDashboardListingsCreateRouteImport
      parentRoute: typeof AgentDashboardListingsRoute
    }
    '/agent/dashboard/listings/$id/edit': {
      id: '/agent/dashboard/listings/$id/edit'
      path: '/$id/edit'
      fullPath: '/agent/dashboard/listings/$id/edit'
      preLoaderRoute: typeof AgentDashboardListingsIdEditRouteImport
      parentRoute: typeof AgentDashboardListingsRoute
    }
  }
}

interface AdminPropertiesRouteChildren {
  AdminPropertiesCreateRoute: typeof AdminPropertiesCreateRoute
}

const AdminPropertiesRouteChildren: AdminPropertiesRouteChildren = {
  AdminPropertiesCreateRoute: AdminPropertiesCreateRoute,
}

const AdminPropertiesRouteWithChildren = AdminPropertiesRoute._addFileChildren(
  AdminPropertiesRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPropertiesRoute: typeof AdminPropertiesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPropertiesRoute: AdminPropertiesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentsRouteChildren {
  AgentsSlugRoute: typeof AgentsSlugRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsSlugRoute: AgentsSlugRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

interface AgentDashboardListingsRouteChildren {
  AgentDashboardListingsCreateRoute: typeof AgentDashboardListingsCreateRoute
  AgentDashboardListingsIdEditRoute: typeof AgentDashboardListingsIdEditRoute
}

const AgentDashboardListingsRouteChildren: AgentDashboardListingsRouteChildren =
  {
    AgentDashboardListingsCreateRoute: AgentDashboardListingsCreateRoute,
    AgentDashboardListingsIdEditRoute: AgentDashboardListingsIdEditRoute,
  }

const AgentDashboardListingsRouteWithChildren =
  AgentDashboardListingsRoute._addFileChildren(
    AgentDashboardListingsRouteChildren,
  )

interface AgentDashboardRouteChildren {
  AgentDashboardBlogRoute: typeof AgentDashboardBlogRoute
  AgentDashboardLeadsRoute: typeof AgentDashboardLeadsRoute
  AgentDashboardListingsRoute: typeof AgentDashboardListingsRouteWithChildren
  AgentDashboardProfileRoute: typeof AgentDashboardProfileRoute
  AgentDashboardReferralsRoute: typeof AgentDashboardReferralsRoute
  AgentDashboardSubscriptionsRoute: typeof AgentDashboardSubscriptionsRoute
  AgentDashboardVerificationRoute: typeof AgentDashboardVerificationRoute
}

const AgentDashboardRouteChildren: AgentDashboardRouteChildren = {
  AgentDashboardBlogRoute: AgentDashboardBlogRoute,
  AgentDashboardLeadsRoute: AgentDashboardLeadsRoute,
  AgentDashboardListingsRoute: AgentDashboardListingsRouteWithChildren,
  AgentDashboardProfileRoute: AgentDashboardProfileRoute,
  AgentDashboardReferralsRoute: AgentDashboardReferralsRoute,
  AgentDashboardSubscriptionsRoute: AgentDashboardSubscriptionsRoute,
  AgentDashboardVerificationRoute: AgentDashboardVerificationRoute,
}

const AgentDashboardRouteWithChildren = AgentDashboardRoute._addFileChildren(
  AgentDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  DiasporaRoute: DiasporaRoute,
  InsightsRoute: InsightsRoute,
  LandRoute: LandRoute,
  MapRoute: MapRoute,
  MarketInsightsRoute: MarketInsightsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RentRoute: RentRoute,
  SavedRoute: SavedRoute,
  ShortletRoute: ShortletRoute,
  AgentDashboardRoute: AgentDashboardRouteWithChildren,
  AgentLoginRoute: AgentLoginRoute,
  AgentRegisterRoute: AgentRegisterRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
